site_name: PeterPortal API Docs

repo_url: https://github.com/icssc-projects/peterportal-public-api
repo_name: icssc-projects/peterportal-public-api

theme:
  name: material
  favicon: images/peter_favicon.png
  logo: images/peter_favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: docs/
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started: Introduction/Getting-Started.md 
  - REST API:
    - Start Here: REST-API/start_here.md
    - Courses: REST-API/courses.md
    - Instructors: REST-API/instructors.md
    - Grades: REST-API/grades.md
    - Schedule of Classes: REST-API/schedule.md
  - GraphQL API:
    - Start Here: GraphQL-API/start_here.md
    - Learn More: GraphQL-API/learn_more.md
    - Playground: /graphql-playground
  - Contributing: 
    - Start Here: Contributing/start_here.md
    - How to Contribute: Contributing/how_to_contribute.md
    - Documenting: Contributing/documenting.md


extra:
  social:
    - icon: fontawesome/brands/medium
      link: https://icsscprojects.medium.com/
    - icon: fontawesome/brands/github
      link: https://github.com/icssc-projects


copyright: Copyright &copy; 2020 - 2021 ICSSC Projects
extra_css:
  - css/termynal.css
  - css/admonitions.css

extra_javascript:
